game:
    BOARD_HEIGHT: 6
    BOARD_WIDTH: 7

    NUMBER_OF_PLAYERS: 2
    WINNING_SEQUENCE_LENGTH: 4

    PLAYER_1_NAME: Human
    PLAYER_2_NAME: Computer

    USE_GUI: True
    USE_MINIMAX: True

    AI_PLAYERS: {PLAYER_2}

ai:
    minimax:
        DEPTH: 3
        CENTER_ARRAY_SCORE_MULTIPLIER: 3
        EVALUATE_SEQUENCE_SCORES: [100, 5, 2, -5]

console:
    EMPTY_SYMBOL: .
    PLAYER_1_SYMBOL: X
    PLAYER_2_SYMBOL: O
    PLAYER_3_SYMBOL: A
    PLAYER_4_SYMBOL: B

gui:
    WINDOW_WIDTH: 700
    WINDOW_HEIGHT: 700

    EMPTY_COLOR: [10, 10, 10]
    PLAYER_1_COLOR: [57, 73, 137] 
    PLAYER_2_COLOR: [78, 160, 174] 
    PLAYER_3_COLOR: [255, 255, 255] 
    PLAYER_4_COLOR: [0, 200, 200]

    BOARD_X: 0
    BOARD_Y: 100
    BOARD_WIDTH: 700
    BOARD_HEIGHT: 600 
    BOARD_COLOR: [59, 46, 90]

    DROP_ZONE_X: 0
    DROP_ZONE_Y: 0
    DROP_ZONE_WIDTH: 700
    DROP_ZONE_HEIGHT: 100 
    DROP_ZONE_COLOR: [10, 10, 10]

    FPS: 60
    PIECE_FALL_SPEED: 20
    DISTANCE_BETWEEN_CIRCLES: 5 

    WINNER_BACKGROUND_COLOR: [0, 0, 0]

    FONT_NAME: dejavusans
    FONT_SIZE: 32
